package com.example.routinereminder.ui.theme

import androidx.compose.ui.graphics.Color

// Placeholder Material 3 Theme Colors
// Replace these with your actual color palette. You can generate a palette using
// the Material Theme Builder (https://m3.material.io/theme-builder)

// Light Theme Colors
val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF21005D)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFCCC2DC)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inverseOnSurface = Color(0xFF313033)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
val md_theme_dark_scrim = Color(0xFF000000)

// Eye Care Theme (Warm) - Example, adjust as needed
val eye_care_warm_primary = Color(0xFF795548) // Brown
val eye_care_warm_onPrimary = Color(0xFFFFFFFF)
val eye_care_warm_surface = Color(0xFFFFF8E1) // Light Yellow/Cream
val eye_care_warm_onSurface = Color(0xFF4E342E) // Dark Brown
val eye_care_warm_background = Color(0xFFFFF3E0) // Light Orange/Cream
val eye_care_warm_onBackground = Color(0xFF4E342E)

object AppPalette {
    val SurfaceStrong = Color(0xFF121212)
    val Surface = Color(0xFF1C1C1C)
    val SurfaceAlt = Color(0xFF2A2A2A)
    val SurfaceElevated = Color(0xFF1B1B1B)
    val SurfaceDeep = Color(0xFF0E0E0E)
    val SurfaceOverlay = Color(0xFF101010)
    val SurfaceDialog = Color(0xFF111111)
    val SurfaceMuted = Color(0xFF151515)
    val SurfaceSubtle = Color(0xFF1A1A1A)
    val SurfaceTrack = Color(0xFF3A3A3A)
    val SurfaceDanger = Color(0xFF3B1B1B)

    val TextPrimary = Color(0xFFEAEAEA)
    val TextSecondary = Color(0xFFB0B0B0)
    val TextMuted = Color(0xFF8A8A8A)
    val TextHint = Color(0xFFBBBBBB)
    val TextDisabled = Color(0xFFCBCBCB)
    val TextLight = Color(0xFFE6E6E6)
    val TextSubtle = Color(0xFFBDBDBD)
    val TextSoft = Color(0xFF888888)
    val TextInverse = Color(0xFFFFFFFF)
    val TextAccent = Color(0xFF0FEEE5)

    val Accent = Color(0xFF1E88E5)
    val AccentStrong = Color(0xFF2196F3)
    val AccentSoft = Color(0x332196F3)
    val AccentSecondary = Color(0xFF4CAF50)
    val AccentSecondarySoft = Color(0x334CAF50)
    val AccentOrangeSoft = Color(0x33FF9800)
    val AccentPinkSoft = Color(0x33E91E63)
    val AccentPink = Color(0xFFE91E63)
    val AccentAmberSoft = Color(0x33FFC107)
    val AccentAmber = Color(0xFFFFC107)
    val AccentPurpleSoft = Color(0x33AA00FF)
    val AccentDeepOrangeSoft = Color(0x33FF5722)
    val AccentDeepOrange = Color(0xFFFF5722)
    val AccentCyan = Color(0xFF00BCD4)
    val Info = Color(0xFF64B5F6)

    val Success = Color(0xFF00C853)
    val Danger = Color(0xFFB3261E)
    val DangerSoft = Color(0xFFFFB4B4)
    val DangerAccent = Color(0xFFE53935)
    val DangerBright = Color(0xFFFF5252)

    val BorderSubtle = Color(0xFF333333)
    val BorderNeutral = Color(0xFF9E9E9E)
    val BorderStrong = Color(0xFF424242)

    val MapLocation = Color(0xFF2196F3)
    val MapTrail = Color(0xFFFF4081)
    val MapStroke = Color(0xFFFFFFFF)
    val MapBackground = Color(0xFF000000)

    val Overlay = Color(0x66000000)
    val TagFallbackSoft = Color(0x33444444)
}
